<div class="container">
	<div class="row">
		<div class="col-12 col-lg-8 single-post">
            <article id="post-<?=$this->news->id;?>" itemscope itemType="http://schema.org/BlogPosting">
                <?php if($this->news->plik){?><img src="<?=$this->baseUrl;?>/files/news/<?=$this->news->plik;?>" alt="<?=$this->news->tytul;?>" itemprop="image"><?php } ?>
                <h1><a href="<?=$this->baseUrl;?>/aktualnosci/<?=$this->news->tag;?>/" title="<?=$this->news->tytul; ?>" itemprop="url"><span itemprop="name headline"><?=$this->news->tytul; ?></span></a></h1>
                <div itemprop="articleBody">
                    <p><b><?=$this->news->wprowadzenie; ?></b></p>
                    <?=replace($this->news->tekst); ?>
                </div>

                <meta itemprop="author" content="<?= $this->header->autor; ?>">
                <meta itemprop="datePublished" content="<?=$this->news->data;?>">
            </article>
		</div>
		<div class="col-12 col-lg-4 pt-5 pt-lg-0 single-post-side">
<?php if($this->inne){?>
			<div class="side-box">
				<ul class="list-unstyled">
<?php foreach($this->inne as $inny){?>
				  <li class="media">
					<a href="<?=$this->baseUrl;?>/aktualnosci/<?=$inny->tag;?>/" title="<?=$inny->tytul;?>">
					<?php if($inny->plik){?><img src="<?=$this->baseUrl;?>/files/news/<?=$inny->plik;?>" alt="<?=$inny->tytul;?>"><?php } ?>
					<div class="media-body">
					  <h5 class=""><?=$inny->tytul;?></h5>
					  <p><?=previewParser($inny->wprowadzenie, 200);?> ...</p>
					</div>
					</a>
				  </li>
<?php } ?>
				</ul>
			</div>
<?php } ?>
<?php if($this->header->fb){?>
			<div class="side-box">
				<h3>Facebook</h3>
				<iframe src="https://www.facebook.com/plugins/page.php?href=<?= urlencode($this->header->fb);?>%2F&tabs=timeline&width=310&height=500&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId=1383589491946459" width="310" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" data-adapt-container-width="true"></iframe>
			</div>
<?php } ?>
		</div>
		
	</div>
</div>