<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<div class="widget">
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="50%">Nazwa</th>
					<th width="40%">Link</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $pozycja) : ?>
				<tr id="recordsArray_<?=$this->escape($pozycja->id);?>">
				<td><?=$this->escape($pozycja->nazwa);?></td>
				<td><?=$this->baseUrl;?>/m/<?=$this->escape($pozycja->tag);?></td>
				<td class="right">
					<a href="<?=$this->baseUrl;?>/admin/mieszkania/edytuj/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnEdit" title="Edytuj wpis"></a>
					<a href="<?=$this->baseUrl;?>/admin/mieszkania/usun/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń wpis"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl;?>/admin/mieszkania/nowa/" class="button greyishBtn">Dodaj mieszkanie</a>
			</div>
		</div>
	</div>
</div>