<div id="dziennik">
	<div class="container">
		<div class="row">
			<div class="col-3 ">
                <div class="inwestmenu">
                    <?php echo $this->render('inwestycja/aside.phtml');?>
                </div>
			</div>
			
			<div class="col-9 single-post">
                <article id="post-<?=$this->news->id;?>" itemscope itemType="http://schema.org/BlogPosting">
                    <?php if($this->news->plik){?><img src="<?=$this->baseUrl;?>/files/inwestycje/news/<?=$this->news->plik;?>" alt="<?=$this->news->tytul;?>" itemprop="image"><?php } ?>
                    <h1><a href="<?=$this->baseUrl;?>/aktualnosci/<?=$this->news->tag;?>/" title="<?=$this->news->tytul; ?>" itemprop="url"><span itemprop="name headline"><?=$this->news->tytul; ?></span></a></h1>
                    <div itemprop="articleBody">
                        <p><b><?=$this->news->wprowadzenie; ?></b></p>
                        <?=replace($this->news->tekst); ?>
                    </div>

                    <meta itemprop="author" content="<?= $this->header->autor; ?>">
                    <meta itemprop="datePublished" content="<?=$this->news->data;?>">
                </article>
			</div>
		</div>
	</div>
</div>