<div id="dziennik">
	<div class="container">
		<div class="row">
			<div class="col-3 inwestmenu">
				<?php echo $this->render('inwestycja/aside.phtml');?>
			</div>

			<div class="col-9 inwestdesc">
			
			<div class="fluid-container">
			<?php foreach($this->news as $key => $post){?>
				<article id="post-<?=$post->id;?>" itemscope itemType="http://schema.org/BlogPosting" class="row no-gutters <?php if($key % 2 == 0) {?><?php } else {?>entry-grey-content<?php } ?>">
				<?php if($key % 2 == 0) {?>
					<?php if($post->plik){?><div class="col-5 col-news-thumb"><a href="<?=$this->baseUrl; ?>/i/<?=$this->wybranytag;?>/w/<?=$post->id;?>,<?=zmiana($post->tytul);?>/" itemprop="url"><img src="<?=$this->baseUrl;?>/files/inwestycje/news/thumbs/<?=$post->plik;?>" alt="<?=$post->tytul;?>"></a></div><?php } ?>
					<div class="<?php if($post->plik){?>col-7 col-news-entry<?php } else {?>col-12<?php } ?>">
						<div class="entry-shadow-content">
							<span class="small"><?=$post->data;?></span>
							<h2><a href="<?=$this->baseUrl; ?>/i/<?=$this->wybranytag;?>/w/<?=$post->id;?>,<?=zmiana($post->tytul);?>/" title="<?=$post->tytul;?>" itemprop="url"><span itemprop="name headline"><?=$post->tytul;?></span></a></h2>
							<div class="entry-content" itemprop="description">
								<p><?=previewParser($post->wprowadzenie, 300);?></p>
								<a href="<?=$this->baseUrl; ?>/i/<?=$this->wybranytag;?>/w/<?=$post->id;?>,<?=zmiana($post->tytul);?>/" title="<?=$post->tytul;?>" class="bttn bttn-blue bttn-more">czytaj więcej</a>
							</div>
						</div>
					</div>
			<?php } else {?>
					<div class="<?php if($post->plik){?>col-7 col-news-entry<?php } else {?>col-12<?php } ?>">
						<div class="entry-shadow-content">
							<span class="small"><?=$post->data;?></span>
							<h2><a href="<?=$this->baseUrl; ?>/i/<?=$this->wybranytag;?>/w/<?=$post->id;?>,<?=zmiana($post->tytul);?>/" title="<?=$post->tytul;?>" itemprop="url"><span itemprop="name headline"><?=$post->tytul;?></span></a></h2>
							<div class="entry-content" itemprop="description">
								<p><?=previewParser($post->wprowadzenie, 300);?></p>
								<a href="<?=$this->baseUrl; ?>/i/<?=$this->wybranytag;?>/w/<?=$post->id;?>,<?=zmiana($post->tytul);?>/" title="<?=$post->tytul;?>" class="bttn bttn-blue bttn-more">czytaj więcej</a>
							</div>
						</div>
					</div>
					<?php if($post->plik){?><div class="col-5 col-news-thumb"><a href="<?=$this->baseUrl; ?>/i/<?=$this->wybranytag;?>/w/<?=$post->id;?>,<?=zmiana($post->tytul);?>/" itemprop="url"><img src="<?=$this->baseUrl;?>/files/inwestycje/news/thumbs/<?=$post->plik;?>" alt="<?=$post->tytul;?>"></a></div><?php } ?>
				<?php } ?>	
				<meta itemprop="author" content="<?= $this->header->autor; ?>">
				<meta itemprop="datePublished" content="<?=$post->data;?>">
				</article>
			<?php } ?>
				<div class="row no-gutters">
					<div class="col-12">
						<?= $this->paginationControl($this->news, 'Sliding', 'pagination.phtml'); ?>
					</div>
				</div>
			</div>

			</div>
		</div>
	</div>
</div>