<div id="plan" class="plan-img">
	<div class="container">
		<div class="row">
			<div class="col-3 inwestmenu">
				<?php echo $this->render('inwestycja/aside.phtml');?>
			</div>
			
			<div class="col-9 inwestdesc inwestroomslist">
				<div class="inwestpadding">
				<?php if($this->inwestycja->id <> 1) {?>
				<div class="plan-holder">
					<div id="canvaplan">
						<img src="<?=$this->baseUrl;?>/files/inwestycje/plan/<?=$this->plan->plik;?>" alt="<?=$this->inwestycja->nazwa;?>" style="max-width:100%;height:auto;" id="myimagemap" usemap="#imagemap">
						<map name="imagemap">
						<?php if($this->inwestycja->typ == 1) {
								foreach($this->budynki as $budynek) {
									$building = str_replace('href=""','href="'.$this->baseUrl.'/i/'.$this->inwestycja->tag.'/b/'.$budynek->id.'/" data-item="'.$budynek->id.'"', $budynek->html);
									$building =  str_replace('shape="polygon"','shape="poly"', $building);
									echo str_replace('alt=""','title="'.$budynek->nazwa.'" alt=""', $building);
								}
						 } ?>
						<?php if($this->inwestycja->typ == 2) {
								foreach($this->pietra as $pietro) {
									$floor =  str_replace('href=""','href="'.$this->baseUrl.'/i/'.$this->inwestycja->tag.'/p/'.$pietro->numer.'/typ/'.$pietro->typ.'/" data-item="'.$pietro->id.'"', $pietro->html);
									$floor =  str_replace('shape="polygon"','shape="poly"', $floor);
									echo str_replace('alt=""','title="'.$pietro->nazwa.'" alt=""', $floor);
								}
						} ?>
						<?php if($this->inwestycja->typ == 3) {
							foreach($this->powierzchnia as $mieszkania) {
							
									$html = $mieszkania->html;
									if($mieszkania->status <> 2) {
										$mieszkanie = str_replace('href=""','href="'.$this->baseUrl.'/i/'.$this->inwestycja->tag.'/d/'.$mieszkania->numer.'/" data-id="'.$mieszkania->id.'"', $html);
									} else {
										$mieszkanie = str_replace('href=""','href="#"', $html);
									}
								
									$mieszkanie =  str_replace('shape="polygon"','shape="poly"', $mieszkanie);

									if($mieszkania->status == 1) {
										$mieszkanie = str_replace('alt=""','id="'.$mieszkania->id.'" alt="" title="<b>'.$mieszkania->nazwa.'</b><br />Powierzchnia: <b class=fr>'.$mieszkania->metry.' m<sup>2</sup></b><br />Pokoje: <b class=fr>'.$mieszkania->pokoje.'</b><br />'.$mdm.''.statusMieszkania($mieszkania->status).'" data-color="green" class="inline forsale"', $mieszkanie);
									}
									if($mieszkania->status == 2) {
										$mieszkanie = str_replace('alt=""','id="'.$mieszkania->id.'" alt="" title="<b>'.$mieszkania->nazwa.'</b><br />Powierzchnia: <b class=fr>'.$mieszkania->metry.' m<sup>2</sup></b><br />Pokoje: <b class=fr>'.$mieszkania->pokoje.'</b><br />'.$mdm.''.statusMieszkania($mieszkania->status).'" data-color="red" class="inline sold"', $mieszkanie);
									}
									if($mieszkania->status == 3) {
										$mieszkanie = str_replace('alt=""','id="'.$mieszkania->id.'" alt="" title="<b>'.$mieszkania->nazwa.'</b><br />Powierzchnia: <b class=fr>'.$mieszkania->metry.' m<sup>2</sup></b><br />Pokoje: <b class=fr>'.$mieszkania->pokoje.'</b><br />'.$mdm.''.statusMieszkania($mieszkania->status).'" data-color="blue" class="inline reserved"', $mieszkanie);
									}
									if($mieszkania->status == 4) {
										$mieszkanie = str_replace('alt=""','id="'.$mieszkania->id.'" alt="" title="<b>'.$mieszkania->nazwa.'</b><br />Powierzchnia: <b class=fr>'.$mieszkania->metry.' m<sup>2</sup></b><br />Pokoje: <b class=fr>'.$mieszkania->pokoje.'</b><br />'.$mdm.''.statusMieszkania($mieszkania->status).'" data-color="orange" class="inline rent"', $mieszkanie);
									}
									echo $mieszkanie;
							}
						} ?>
						</map>
					</div>
				</div>
				<?php } ?>
				
				<div class="lista"><div class="view"><span id="grid">Mała lista</span> <span id="list">Duża lista</span></div></div>
	
				<div id="offerList" class="fluid-container">
					<?php if($this->wynik > 0){?>
						<?php foreach($this->powierzchnia as $powierzchnia){?>
						
						<!-- Osiedlowa -->
						<?php if($this->inwestycja->typ == 1) {?>
							<div class="row no-gutters pozycja-ap d-flex align-items-center justify-content-start" data-id="<?=$powierzchnia->numer;?>" data-url="<?=$this->baseUrl;?>/i/<?=$this->inwestycja->tag?>/b/<?=$powierzchnia->id_budynek;?>/p/<?=$powierzchnia->numer_pietro;?>/m/<?=$powierzchnia->numer;?>/">
						<?php } ?>
						
						<!-- Budynkowa -->
						<?php if($this->inwestycja->typ == 2) {?>
							<div class="row no-gutters pozycja-ap d-flex align-items-center justify-content-start" data-id="<?=$powierzchnia->numer;?>" data-url="<?=$this->baseUrl;?>/i/<?=$this->inwestycja->tag?>/p/<?=$powierzchnia->numer_pietro;?>/m/<?=$powierzchnia->numer;?>/">
						<?php } ?>
						
						<!-- Domki -->
						<?php if($this->inwestycja->typ == 3) {?>
							<div class="row no-gutters pozycja-ap d-flex align-items-center justify-content-start" data-id="<?=$powierzchnia->numer;?>" data-url="<?=$this->baseUrl;?>/i/<?=$this->inwestycja->tag?>/d/<?=$powierzchnia->numer;?>/">
						<?php } ?>
						
						
							<!-- Osiedlowa i budynkowa -->
							<div class="col-2 status-ap-<?=statusMieszkaniaListaTag($powierzchnia->status);?> namelist">
								<h2><?=$powierzchnia->numer;?></h2>
							</div>
							<div class="col-2 col-room-thumb">
								<img src="<?=$this->baseUrl;?>/files/inwestycje/pomieszczenie/thumbs/<?=$powierzchnia->plik;?>" alt="<?=$powierzchnia->nazwa;?>">
							</div>
							<div class="col-3 paramlist">
								<ul class="list-unstyled biglist mb-0">
									<li>pokoje: <span><?=$powierzchnia->pokoje;?></span></li>
									<li>powierzchnia: <span><?=$powierzchnia->metry;?>&nbsp; m<sup>2</sup></span></li>
								<?php if($powierzchnia->numer_pietro){?><li class="li-inwest-rwd">piętro: <span><?=$powierzchnia->numer_pietro;?></span></li><?php } ?>
								</ul>

								<ul class="list-unstyled smalllist mb-0">
									<li>pokoje: <span><?=$powierzchnia->pokoje;?></span></li>
									<li>pow.: <span><?=$powierzchnia->metry;?>&nbsp; m<sup>2</sup></span></li>
									<li>piętro: <span><?=$powierzchnia->numer_pietro;?></span></li>
								</ul>
							</div>
							<div class="col-2 text-right">
								<div class="<?=statusMieszkaniaListaTag($powierzchnia->status);?>-ap"><?=statusMieszkania($powierzchnia->status);?><?php if($powierzchnia->specjalny){?><br><div class="specjalny-ap"><?=$powierzchnia->specjalny;?></div><?php } ?></div>
							</div>
							<div class="col-3 text-right d-flex align-items-center justify-content-end">
							<!--<h4>380.000 zł</h4>-->
								<!-- Osiedlowa -->
								<?php if($this->inwestycja->typ == 1) {?>
									<a href="<?=$this->baseUrl;?>/i/<?=$this->inwestycja->tag?>/b/<?=$powierzchnia->id_budynek;?>/p/<?=$powierzchnia->numer_pietro;?>/m/<?=$powierzchnia->numer;?>/" class="bttn bttn-blue bttn-small" target="_blank">ZOBACZ</a>						
								<?php } ?>
								
								<!-- Budynkowa -->
								<?php if($this->inwestycja->typ == 2) {?>
									<a href="<?=$this->baseUrl;?>/i/<?=$this->inwestycja->tag?>/p/<?=$powierzchnia->numer_pietro;?>/m/<?=$powierzchnia->numer;?>/" class="bttn bttn-blue bttn-small" target="_blank">ZOBACZ</a>
								<?php } ?>
								
								<!-- Domki -->
								<?php if($this->inwestycja->typ == 3) {?>
									<a href="<?=$this->baseUrl;?>/i/<?=$this->inwestycja->tag?>/d/<?=$powierzchnia->numer;?>/" class="bttn bttn-blue bttn-small" target="_blank">ZOBACZ</a>
								<?php } ?>
							</div>
						</div>
						<?php } ?>
					<?php } else {?>
						<div class="col-12 text-center">
							<p><br>Brak wyników</p>
						</div>
					<?php } ?>
				</div>
				</div>
			</div>
		</div>
	</div>
</div>