<div id="finansowanie">
	<div class="fluid-container">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="source mb-2 mt-0">Czego możesz oczekiwać od naszego eksperta?</h2>
				<p class="mb-3">W ramach zakupu mieszkania możesz u nas skorzystać z bezpłatnych konsultacji finansowych.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-6">
				<ul class="list-unstyled checklist">
					<li>wstępna analiza zdolności kredytowej</li>
				</ul>
			</div>
			<div class="col-6">
				<ul class="list-unstyled checklist">
					<li>wybór najlepszej dla Ciebie oferty kredytowej dostępnej na rynku bankowym</li>
				</ul>
			</div>
		</div>
		
		<div class="row">
			<div class="col-6">
				<ul class="list-unstyled checklist">
					<li>pomoc w wypełnianiu wszelkich niezbędne dokumentów i formularzy bankowych</li>
				</ul>
			</div>
			<div class="col-6">
				<ul class="list-unstyled checklist">
					<li>opieka od momentu złożenia wniosku kredytowego do uruchomienia środków</li>
				</ul>
			</div>
		</div>
		
		<div class="row">
			<div class="col-6">
				<ul class="list-unstyled checklist">
					<li>mobilność - określ miejsce spotkania –  biuro, dom, a może kawa na mieście - nasz ekspert spotka się z Toba tam, gdzie będzie Ci najwygodniej</li>
				</ul>
			</div>
		</div>
		
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="source">Co zyskujesz?</h2>
			</div>
		</div>
		
		<div class="row">
			<div class="col-4 text-center">
				<div class="potrzeba">
					<div class="circle-icon"><img src="<?=$this->baseUrl;?>/files/upload/pieniadze-icon.png" alt="Pieniądze"></div>
					<h4>pieniądze</h4>
					<p>kupując u nas mieszkanie możesz bezpłatnie skorzystać z usług naszego eksperta finansowego</p>
				</div>
			</div>
			<div class="col-4 text-center">
				<div class="potrzeba">
					<div class="circle-icon"><img src="<?=$this->baseUrl;?>/files/upload/czas-icon.png" alt="Czas"></div>
					<h4>czas</h4>
					<p>podczas jednej wizyty w miejscu, które wskażesz, otrzymujesz zestawienie propozycji bankowych bankowych z najkorzystniejszą opcją dla Ciebie</p>
				</div>
			</div>
			<div class="col-4 text-center">
				<div class="potrzeba">
					<div class="circle-icon"><img src="<?=$this->baseUrl;?>/files/upload/spokoj-icon.png" alt="Spokój"></div>
					<h4>spokój</h4>
					<p>nasz ekspert profesjonalnie zajmie się Twoją dokumentacją kredytową i doprowadzi do celu, jakim jest otrzymanie środków na zakup mieszkania</p>
				</div>
			</div>
		</div>
		
		<div class="row">
			<div class="col-12"><hr class="mt-5 mb-5"></div>
		</div>
		
		<div class="row">
			<div class="col-12 pl-5 text-center">
				<p>Nasz ekspert</p>
				<h2 class="source mt-0">Norbert Korczyński</h2>
				<ul>
					<li>posiada zezwolenie Komisji Nadzoru Finansowego na prowadzenie działalności w zakresie pośrednictwa kredytowego</li>
					<li>praktyk z kilkunastoletnim doświadczeniem w pracy w bankach</li>
				</ul>
				<p><a href="tel:503689221">tel. 503-68-92-21</a> / <a href="mailto:norbert.korczynski@finars.pl">norbert.korczynski@finars.pl</a></p>
			</div>
		</div>
		
		<div class="row">
			<div class="col-12"><hr class="mt-5 mb-5"></div>
		</div>
		
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="source mb-2">Otwarty Rachunek Powierniczy</h2>
				<p class="mb-5">Twoje pieniądze są bezpieczne</p>
			</div>
		</div>
		
		<div class="row">
			<div class="col-12 pb-2">
				<p>Zgodnie z ustawą deweloperską z dnia 16.09.2011r. o ochronie praw nabywcy lokalu mieszkalnego lub domu jednorodzinnego (<a href="http://prawo.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20112321377" target="_blank">link do ustawy</a>) -  zapewniamy naszym klientom ochronę ich pieniędzy w postaci otwartego rachunku powierniczego. W tym zakresie podjęliśmy współpracę z mBankiem.</p>
				<p>&nbsp;</p>
				<p><b>Na czym to polega?</b></p>
			</div>
		</div>
		
		<div class="row">
			<div class="col-12">
				<ul class="list-unstyled checklist infolist">
					<li>otwarty rachunek powierniczy należy do dewelopera</li>
				</ul>
			</div>
			<div class="col-12">
				<ul class="list-unstyled checklist infolist">
					<li>służy on do gromadzenia środków wpłacanych przez nabywców na cele określone w umowie deweloperskiej</li>
				</ul>
			</div>
			<div class="col-12">
				<ul class="list-unstyled checklist infolist">
					<li>bank ewidencjonuje wpłaty i wypłaty odrębnie dla każdego nabywcy</li>
				</ul>
			</div>
			<div class="col-12">
				<ul class="list-unstyled checklist infolist">
					<li>indywidualny numer rachunku (subkonto) powiązanego z rachunkiem powierniczym dewelopera, na który nabywca będzie dokonywał wpłaty jest wskazany w umowie deweloperskiej</li>
				</ul>
			</div>
		</div>
		
		<div class="row">
			<div class="col-12">
				<ul class="list-unstyled checklist infolist">
					<li>wypłata zdeponowanych środków następuje zgodnie z harmonogramem przedsięwzięcia deweloperskiego określonego w umowie deweloperskiej</li>
				</ul>
			</div>
			<div class="col-12">
				<ul class="list-unstyled checklist infolist">
					<li>bank dokonuje kontroli zakończenia każdego z etapów przedsięwzięcia deweloperskiego, przed dokonaniem wypłaty z otwartego  rachunku powierniczego na rzecz dewelopera, na podstawie wpisu kierownika budowy w dzienniku budowy, potwierdzonego przez wyznaczoną przez bank osobę posiadającą odpowiednie uprawnienia budowlane</li>
				</ul>
			</div>
		</div>
		
		<div class="row">
			<div class="col-12">
				<ul class="list-unstyled checklist infolist">
					<li>bank wypłaca deweloperowi zgromadzone na rachunku powierniczym środki po stwierdzeniu zakończenia danego etapu realizacji przedsięwzięcia deweloperskiego</li>
				</ul>
			</div>
		</div>
		
		
	</div>
</div>