<div id="ofertyspecjalne">
<?php foreach($this->specjalne as $key => $specjalna){?>
	<div class="oferta-specjalna" style="background:url('<?=$this->baseUrl;?>/files/specjalne/<?=$specjalna->plik;?>') no-repeat center top">
		<div class="container">
			<div class="row<?php if($key % 2 == 0) {?><?php } else {?> justify-content-end<?php } ?>">
				<div class="col-6">
					<div class="gradient">
						<h2><?=$specjalna->nazwa;?></h2>
						<p><?=$specjalna->wprowadzenie;?></p>
						<a href="<?=$this->baseUrl;?>/oferta/<?=$specjalna->tag;?>/" class="hvr-ripple-out hvr-ripple-out-white">Czytaj więcej</a>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php } ?>
</div>