<div id="aboutus" class="pt-0">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <p>Madey Development spółka z ograniczoną odpowiedzialnością to firma wchodząca w skład Grupy Madej. W tej grupie wiodącą rolę odgrywa firma Madej Bud - wykonawca obiektów kubaturowych i inżynieryjnych.</p>
                <p>Wieloletnie doświadczenie, które zdobyliśmy na placach budowy najróżniejszych budynków w całej Polsce dało nam podstawy aby zająć się kompleksowo budowaniem - począwszy od zakupu działki, poprzez wybór projektu architektonicznego, wykonanie budynku i przekazanie do użytkowania.</p>
                <p>Dzięki silnej pozycji na rynku i realizacji wielu trudnych i wymagających projektów gwarantujemy jakość, partnerskie podejście i zaufanie, które możesz nam powierzyć.</p>
            </div>
        </div>
    </div>

    <div class="about-paralaxa">
        <div class="container">
            <div class="row inwestor-icons">
                <div data-aos-offset="300" data-aos-delay="300" data-aos="fade-up" class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/kompleksowe.png" width="100" height="100" alt="">
                        <h3>Kompleksowe Podejście</h3>
                    </div>
                </div>
                <div data-aos-offset="300" data-aos-delay="400" data-aos="fade-up" class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/zaufanie.png" width="100" height="100" alt="">
                        <h3>Zaufanie</h3>
                    </div>
                </div>
                <div data-aos-offset="300" data-aos-delay="500" data-aos="fade-up" class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/partner.png" width="100" height="100" alt="">
                        <h3>Partnerskie Podejście</h3>
                    </div>
                </div>
                <div data-aos-offset="300" data-aos-delay="600" data-aos="fade-up" class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/jakosc.png" width="100" height="100" alt="">
                        <h3>Gwarancja Jakości</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mb-5">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <span>Inwestor</span>
                    <h2>Wieloletnie doświadczenie w budownictwie</h2>
                </div>
            </div>
            <div class="col-12">
                <?=replace('[galeria=galeria]1[/galeria]'); ?>
            </div>
        </div>
    </div>
</div>

<div class="container mb-5">
    <div class="row">
        <div class="col-12">
            <div class="section-title">
                <span>Diamenty Forbesa 2022</span>
                <h2>II miejsce w Diamentach Forbesa 2022</h2>
            </div>
        </div>

        <div class="col-12 text-center">
            <p>Dziękujemy bardzo za wyróżnienie Madey Bud jako diamentowej firmy z województwa łódzkiego</p>
            <img src="<?=$this->baseUrl;?>/public/gfx/template/diamenty-miesiecznika-forbes-2022.png" alt="Logo Diamenty Forbesa 2022" style="margin: 40px auto">
            <a href="https://www.forbes.pl/diamenty/2022/artykuly/diamenty-forbesa-2022-oto-najlepsze-firmy-z-wojewodztwa-lodzkiego/56ggtjs" target="_blank">https://www.forbes.pl/diamenty/2022/artykuly/diamenty-forbesa-2022-oto-najlepsze-firmy-z-wojewodztwa-lodzkiego/56ggtjs</a>
        </div>
    </div>
</div>

<div id="investdone">
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <span>Nasze inwestycje</span>
                    <h2>Inwestycje zrealizowane</h2>
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <?php foreach($this->inwestycje as $inwestycja){?>
                        <div class="inwest-list-item col-6">
                            <img src="<?=$this->baseUrl;?>/files/inwestycje/tekst/<?=$inwestycja->inwestycja_plik;?>" alt="<?=$inwestycja->nazwa;?>">
                            <div class="inwestlist">
                                <h2 class="source"><?=$inwestycja->nazwa;?></h2>
                                <p><?=$inwestycja->lista;?></p>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>