<div id="aboutus" class="pt-0">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <p>Madey Development spółka z ograniczoną odpowiedzialnością to firma wchodząca w skład Grupy Madej. W tej grupie wiodącą rolę odgrywa firma Madej Bud - wykonawca obiektów kubaturowych i inżynieryjnych.</p>
                <p>Wieloletnie doświadczenie, które zdobyliśmy na placach budowy najróżniejszych budynków w całej Polsce dało nam podstawy aby zająć się kompleksowo budowaniem - począwszy od zakupu działki, poprzez wybór projektu architektonicznego, wykonanie budynku i przekazanie do użytkowania.</p>
                <p>Dzięki silnej pozycji na rynku i realizacji wielu trudnych i wymagających projektów gwarantujemy jakość, partnerskie podejście i zaufanie, które możesz nam powierzyć.</p>
            </div>
        </div>
    </div>

    <div class="about-paralaxa">
        <div class="container">
            <div class="row inwestor-icons">
                <div class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/kompleksowe.png" width="100" height="100" alt="">
                        <h3>Kompleksowe Podejście</h3>
                    </div>
                </div>
                <div class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/zaufanie.png" width="100" height="100" alt="">
                        <h3>Zaufanie</h3>
                    </div>
                </div>
                <div class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/partner.png" width="100" height="100" alt="">
                        <h3>Partnerskie Podejście</h3>
                    </div>
                </div>
                <div class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/jakosc.png" width="100" height="100" alt="">
                        <h3>Gwarancja Jakości</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <span>Inwestor</span>
                    <h2>Wieloletnie doświadczenie w budownictwie</h2>
                </div>
            </div>
            <div class="col-12">
                <?=replace('[galeria=galeria]1[/galeria]'); ?>
            </div>
        </div>
    </div>

</div>