<div id="aboutus" class="pt-0">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <p>Madey Development spółka z ograniczoną odpowiedzialnością to firma wchodząca w skład Grupy Madej. W tej grupie wiodącą rolę odgrywa firma Madej Bud - wykonawca obiektów kubaturowych i inżynieryjnych.</p>
                <?=replace('[galeria=galeria]43[/galeria]'); ?>
                <p>Jesteśmy odpowiedzialną firmą z ugruntowaną pozycją na rynku. Wspólnie tworzymy trwałe i nowoczesne konstrukcje. Główna Siedziba firmy znajduje się na ulicy Przybyszewskiego 199/205 w Łodzi.</p>

                <p>Wieloletnie doświadczenie, które zdobyliśmy na placach budowy najróżniejszych budynków w całej Polsce dało nam podstawy aby zająć się kompleksowo budowaniem - począwszy od zakupu działki, poprzez wybór projektu architektonicznego, wykonanie budynku i przekazanie do użytkowania.</p>
                <p>Dzięki silnej pozycji na rynku i realizacji wielu trudnych i wymagających projektów gwarantujemy jakość, partnerskie podejście i zaufanie, które możesz nam powierzyć.</p>
            </div>
        </div>
    </div>

    <div class="about-paralaxa">
        <div class="container">
            <div class="row inwestor-icons">
                <div class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/kompleksowe.png" width="100" height="100" alt="">
                        <h3>Kompleksowe Podejście</h3>
                    </div>
                </div>
                <div class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/zaufanie.png" width="100" height="100" alt="">
                        <h3>Zaufanie</h3>
                    </div>
                </div>
                <div class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/partner.png" width="100" height="100" alt="">
                        <h3>Partnerskie Podejście</h3>
                    </div>
                </div>
                <div class="col-3">
                    <div class="paralaxa-box">
                        <img src="/files/upload/jakosc.png" width="100" height="100" alt="">
                        <h3>Gwarancja Jakości</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mb-5">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <span>Inwestor</span>
                    <h2>Wieloletnie doświadczenie w budownictwie</h2>
                </div>
            </div>
            <div class="col-12">
                <?=replace('[galeria=galeria]1[/galeria]'); ?>
            </div>
        </div>
    </div>
</div>

<div class="container mb-5">
    <div class="row">
        <div class="col-12">
            <div class="section-title">
                <span>Nasze nagrody</span>
                <h2>Diamenty Forbesa</h2>
                <p>Dziękujemy bardzo za wyróżnienie Madey Bud jako diamentowej firmy z województwa łódzkiego</p>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-4 text-center">
            <a href="https://www.forbes.pl/diamenty/najszybciej-rozwijajace-sie-polskie-firmy-diamenty-forbesa-2021/z8s9tb5" target="_blank"><img src="<?=$this->baseUrl;?>/public/gfx/template/320x251_forbes_2021.jpg" alt="Logo Diamenty Forbesa 2021" style="margin: 40px auto"></a>
            <a href="https://www.forbes.pl/diamenty/najszybciej-rozwijajace-sie-polskie-firmy-diamenty-forbesa-2021/z8s9tb5" target="_blank" class="bttn bttn-blue bttn-more">CZYTAJ WIĘCEJ</a>
        </div>
        <div class="col-1">&nbsp;</div>
        <div class="col-4 text-center">
            <a href="https://www.forbes.pl/diamenty/2022/artykuly/diamenty-forbesa-2022-oto-najlepsze-firmy-z-wojewodztwa-lodzkiego/56ggtjs" target="_blank"><img src="<?=$this->baseUrl;?>/public/gfx/template/diamenty-miesiecznika-forbes-2022-kolor.png" alt="Logo Diamenty Forbesa 2022" style="margin: 40px auto"></a>
            <a href="https://www.forbes.pl/diamenty/2022/artykuly/diamenty-forbesa-2022-oto-najlepsze-firmy-z-wojewodztwa-lodzkiego/56ggtjs" target="_blank" class="bttn bttn-blue bttn-more">CZYTAJ WIĘCEJ</a>
        </div>
    </div>
</div>

<div id="investdone">
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <span>Nasze inwestycje</span>
                    <h2>Inwestycje zrealizowane</h2>
                </div>
            </div>
            <div class="col-12 mt-3">
                <div class="row">
                    <?php foreach($this->inwestycje as $inwestycja){?>
                        <div class="inwest-list-item col-4">
                            <div class="flip-card">
                                <div class="flip-card-inner text-center">
                                    <div class="flip-card-front">
                                        <div>
                                            <img src="<?=$this->baseUrl;?>/files/inwestycje/tekst/<?=$inwestycja->inwestycja_plik;?>" alt="<?=$inwestycja->nazwa;?>">
                                            <div class="inwestlist pb-0">
                                                <h2 class="source mb-0"><?=$inwestycja->nazwa;?></h2>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="flip-card-back">
                                        <div>
                                            <p><?=$inwestycja->flip;?></p>
                                            <a href="<?= $this->baseUrl; ?>/i/<?= $inwestycja->tag; ?>/" class="bttn bttn-blue bttn-more mt-4">ZOBACZ WIĘCEJ</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>