<div id="contact">
    <div class="contact-form">
        <div class="container">
            <?php if($this->message == 1) :?>
                <div class="row">
                    <div id="formalert" class="col-12">
                        <div class="sendok"><p>Twoja wiadomość została wysłana. W najbliższym czasie skontaktujemy się z Państwem celem omówienia szczegółów!</p></div>
                    </div>
                </div>
            <?php endif; ?>
            <form class="validateform" method="post">
                <div class="row">
                    <div class="col-4 input">
                        <label for="form_imie">Imię</label>
                        <input type="text" name="imie" id="form_imie" class="validate[required]" data-prompt-position="topLeft:0" required>
                    </div>
                    <div class="col-4 input">
                        <label for="form_email">E-mail</label>
                        <input type="email" name="email" id="form_email" class="validate[required]" data-prompt-position="topLeft:0" required>
                    </div>
                    <div class="col-4 input">
                        <label for="form_telefon">Telefon</label>
                        <input type="tel" name="telefon" id="form_telefon" class="validate[required]" data-prompt-position="topLeft:0" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 input">
                        <label for="form_wiadomosc">Treść wiadomości</label>
                        <textarea name="wiadomosc" cols="30" rows="10" id="form_wiadomosc" class="validate[required]" data-prompt-position="topLeft:0" required></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 obowiazek">
                        <?=$this->rodo->obowiazek;?>
                    </div>

                    <div class="col-12 rules">
                        <?php foreach($this->regulkis as $regulka){?>
                            <label for="zgoda_<?=$regulka['id'];?>" class="rules-text"><input name="zgoda_<?=$regulka['id'];?>" id="zgoda_<?=$regulka['id'];?>" value="1" type="checkbox" <?php if($regulka['wymagane'] == 1){;?>class="validate[required]"<?php } ?> data-prompt-position="topLeft:0"><p><?=$regulka['tresc'];?></p></label>
                            <div class="clr"></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-center pt-4">
                        <script type="text/javascript">
                            document.write("<button type=\"submit\" class=\"bttn bttn-lg\">WYŚLIJ WIADOMOŚĆ</button>");
                        </script>
                        <noscript><p><b>Do poprawnego działania, Java musi być włączona.</b><p></noscript>
                    </div>
                </div>
            </form>
        </div>
    </div>

	<div class="container pt-5 pb-5 mt-4 mb-4">
		<div class="row">
			<div class="col-8 text-center contact-text">
				<?php replace($this->strona->tekst); ?>

                <div class="col-12">
                    <div class="section-title">
                        <span>Inwestor</span>
                        <h2>Madey Development spółka z ograniczoną odpowiedzialnością sp.k.</h2>
                    </div>
                </div>
                <h3 class="mb-5"><a href="tel:576117119"><b class="blue">576 117 119</b></a></h3>
                <h4>Biuro sprzedaży:</h4>
                <p>ul. Kazimierza Odnowiciela 13</p>

                <div class="row d-flex justify-content-center mt-5">
                    <div class="col-6">
                        <div class="person text-center">
                            <i class="las la-phone-square-alt"></i>
                            <h4>
                                <a href="tel:534664737">Sylwia: 534-664-737</a>
                            </h4>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="person text-center">
                            <i class="las la-phone-square-alt"></i>
                            <h4>
                                <a href="tel:882482077">Ewelina: 882-482-077</a>
                            </h4>
                        </div>

                    </div>
                </div>

            </div>
            <div class="col-4">
                <div class="side-box godziny">
                    <h3>Godziny pracy</h3>
                    <ul class="list-unstyled mb-0">
                        <li>Poniedziałek<span>8:00 - 19:00</span></li>
                        <li>Wtorek<span>8:00 - 19:00</span></li>
                        <li>Środa<span>8:00 - 19:00</span></li>
                        <li>Czwartek<span>8:00 - 19:00</span></li>
                        <li>Piątek<span>9:00 - 18:00</span></li>
                        <li>Sobota<span>9:00 - 15:00</span></li>
                        <li>Niedziela<span class="red">Nieczynne</span></li>
                    </ul>
                </div>
            </div>
		</div>
	</div>
	<div class="fluid-container">
		<div class="row no-gutters">
			<div class="col-12">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5546.520430481595!2d19.56024989853064!3d51.73863132149099!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471a33292f02b697%3A0x5c950ed89fdf0e9e!2sKazimierza%20Odnowiciela%2013%2C%2092-414%20%C5%81%C3%B3d%C5%BA!5e0!3m2!1spl!2spl!4v1641270415294!5m2!1spl!2spl" width="100%" height="350" style="border:0" allowfullscreen="" loading="lazy"></iframe>
			</div>
		</div>
	</div>
</div>

