<div id="contact">
    <div class="contact-form">
        <div class="container">
            <?php if($this->message == 1) :?>
                <div class="row">
                    <div id="formalert" class="col-12">
                        <div class="sendok"><p>Twoja wiadomość została wysłana. W najbliższym czasie skontaktujemy się z Państwem celem omówienia szczegółów!</p></div>
                    </div>
                </div>
            <?php endif; ?>
            <form class="validateform" method="post">
                <div class="row">
                    <div class="col-12 col-sm-6 col-md-4 input">
                        <label for="form_imie">Imię</label>
                        <input type="text" name="imie" id="form_imie" class="validate[required]" data-prompt-position="topLeft:0" required>
                    </div>
                    <div class="col-12 col-sm-6 col-md-4 input">
                        <label for="form_email">E-mail</label>
                        <input type="email" name="email" id="form_email" class="validate[required]" data-prompt-position="topLeft:0" required>
                    </div>
                    <div class="col-12 col-sm-12 col-md-4 input">
                        <label for="form_telefon">Telefon</label>
                        <input type="tel" name="telefon" id="form_telefon" class="validate[required]" data-prompt-position="topLeft:0" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 input">
                        <label for="form_wiadomosc">Treść wiadomości</label>
                        <textarea name="wiadomosc" cols="30" rows="10" id="form_wiadomosc" class="validate[required]" data-prompt-position="topLeft:0" required></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 obowiazek">
                        <?=$this->rodo->obowiazek;?>
                    </div>

                    <div class="col-12 rules">
                        <?php foreach($this->regulkis as $regulka){?>
                            <label for="zgoda_<?=$regulka['id'];?>" class="rules-text"><input name="zgoda_<?=$regulka['id'];?>" id="zgoda_<?=$regulka['id'];?>" value="1" type="checkbox" <?php if($regulka['wymagane'] == 1){;?>class="validate[required]"<?php } ?> data-prompt-position="topLeft:0"><p><?=$regulka['tresc'];?></p></label>
                            <div class="clr"></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-center pt-4">
                        <script type="text/javascript">
                            document.write("<button type=\"submit\" class=\"bttn bttn-lg\">WYŚLIJ WIADOMOŚĆ</button>");
                        </script>
                        <noscript><p><b>Do poprawnego działania, Java musi być włączona.</b><p></noscript>
                    </div>
                </div>
            </form>
        </div>
    </div>

	<div class="container pt-3 pt-sm-5 pb-3 pb-sm-5 mt-4 mb-4">
		<div class="row">
			<div class="col-12 col-lg-8 text-center contact-text">
				<?=replace($this->strona->tekst); ?>
            </div>
            <div class="col-12 col-lg-4 mt-4 mt-lg-0">
                <div class="side-box godziny">
                    <h3>Godziny pracy</h3>
                    <ul class="list-unstyled mb-0">
                        <li class="red"><b>Od 23.01 do 26.01 i 30.01</b><span>8:00 - 19:00</span></li>
                        <li>Poniedziałek<span><?= $this->header->godz_pon; ?></span></li>
                        <li>Wtorek<span><?= $this->header->godz_wt; ?></span></li>
                        <li>Środa<span><?= $this->header->godz_srd; ?></span></li>
                        <li>Czwartek<span><?= $this->header->godz_czw; ?></span></li>
                        <li>Piątek<span><?= $this->header->godz_pt; ?></span></li>
                        <li>Sobota<span><?= $this->header->godz_sb; ?></span></li>
                        <li>Niedziela<span class="red"><?= $this->header->godz_nd; ?></span></li>
                    </ul>
                </div>
            </div>
		</div>
	</div>
	<div class="fluid-container">
		<div class="row no-gutters">
			<div class="col-12">
                <?= $this->header->map_link; ?>
			</div>
		</div>
	</div>
</div>

