<footer>
    <div id="footer">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-1 p-3 p-md-0">
                    <a href="<?=$this->baseUrl;?>/" title="<?= $this->header->nazwa; ?>">
                        <img src="<?=$this->gfxUrl();?>/template/madey-footer-logo.png" alt="<?= $this->header->nazwa; ?>" width="106" height="86">
                    </a>
                </div>
                <div class="col-12 col-sm-6 d-flex align-items-center justify-content-center justify-content-md-start">
                    <div class="text-left pl-0 pl-md-5">
                        <p><?= $this->header->stopka; ?></p>
                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-5 d-flex align-items-center justify-content-center justify-content-md-end">
                    <div class="text-right">
                        <p>Realizacja: <a href="https://www.4dl.pl/" title="4DL Agencja Reklamowa, Agencja Interaktywna, Agencja Marketingowa Warszawa | Agencja reklamowa 4dl.pl" target="_blank">4DL.pl</a> / Powered by: <a href="https://www.developro.pl/" title="System dla Deweloperów | DeveloPRO - Marketing Nieruchomości" target="_blank">DeveloPro</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<div id="cookies"><p><a href="" class="closecookies gradient">Zamknij</a><?= $this->header->cookies; ?></p></div>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">