<div id="megamenu-opacity"></div>
<header>
	<div class="header-holder">
		<div id="header" class="clearfix">
			<div id="logo"><a href="<?=$this->baseUrl;?>/" title="<?= $this->header->nazwa; ?>"><img src="<?=$this->baseUrl;?>/public/gfx/template/logo-kolor.png" alt="<?= $this->header->nazwa; ?>"></a></div>
			<nav class="navbar clearfix">
				<ul class="nav justify-content-end">
					<li><a href="<?=$this->baseUrl;?>/">STRONA GŁÓWNA</a></li>
					<li><a href="<?=$this->baseUrl;?>/oferta/">ZNAJDŹ MIESZKANIE</a></li>
					<li><a href="<?=$this->baseUrl;?>/inwestor/">INWESTOR</a></li>
					<li><a href="<?=$this->baseUrl;?>/aktualnosci/">AKTUALNOŚCI</a></li>
					<li><a href="<?=$this->baseUrl;?>/kontakt/">KONTAKT</a></li>
					<li class="phoneli"><a href="tel:534664737">534-664-737</a></li>
				</ul>
			</nav>
			<div class="mobilemenu"><a href="#" id="triggermenu">MENU</a></div>
		</div>
	</div>
</header>