<div class="header-holder">
    <header>
        <div class="container position-relative">
            <div class="row">
                <div class="col-2 p-0">
                    <div id="logo">
                        <a href="<?=$this->baseUrl;?>/" title="<?= $this->header->nazwa; ?>">
                            <img src="<?=$this->baseUrl;?>/public/gfx/template/logo.png" alt="<?= $this->header->nazwa; ?>" width="240" height="194">
                        </a>
                    </div>
                </div>
                <div class="col-10 p-0">
                    <div class="row">
                        <div class="col-12">
                            <div class="top">
                                <ul class="mb-0 list-unstyled d-flex justify-content-end">
                                    <li><a href="https://www.google.com/maps/dir//Kazimierza+Odnowiciela+13+92-414+%C5%81%C3%B3d%C5%BA/@51.7394061,19.5625714,15z/data=!4m5!4m4!1m0!1m2!1m1!1s0x471a332ec5c3a4df:0x5576542c66d84d74" target="_blank"><i class="fa-icons fa-marker"></i> ul. Kazimierza Odnowiciela 13</a></li>
                                    <li><a href="<?=$this->baseUrl;?>/kontakt/"><i class="fa-icons fa-clock"></i> Pon - Cz: 8:00 - 19:00</a></li>
                                    <li><a href="<?=$this->baseUrl;?>/kontakt/"><i class="fa-icons fa-clock"></i> Pt: 9:00 - 18:00</a></li>
                                    <li><a href="<?=$this->baseUrl;?>/kontakt/"><i class="fa-icons fa-clock"></i> Sb: 9:00 - 15:00</a></li>
                                    <li class="ml-3"><a href="<?=$this->baseUrl;?>/kontakt/"><i class="fa-icons fa-mail"></i></a></li>
                                    <li class="ml-2"><a href="https://www.facebook.com/MadeyDevelopment" target="_blank"><i class="fa-icons fa-fb"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12">
                            <nav class="navbar clearfix">
                                <div class="mobilemenu">
                                    <a href="#" id="triggermenu">MENU</a>
                                </div>
                                <ul class="nav justify-content-end">
                                    <li><a href="<?=$this->baseUrl;?>/">Strona główna</a></li>
                                    <?php $menu = Zend_Registry::get('querymenu'); echo $menu->get_menu_html(0); ?>
                                    <li class="forbesli">
                                        <a href="<?=$this->baseUrl;?>/diamenty-forbesa/" id="forbes">
                                            <img src="<?=$this->baseUrl;?>/public/gfx/template/diamenty-miesiecznika-forbes-2022.png" alt="Logo Diamenty Forbesa 2022">
                                        </a>
                                    </li>
                                    <li class="phoneli">
                                        <a href="tel:576117119">
                                            <span>ZADZWOŃ DO NAS</span>
                                            576-117-119
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
</div>
<div id="megamenu-opacity"></div>